datasets:
  dataset_name: mnistUnbal
  data_folder: data/mnist
  dataset_func: mnist_unbalanced_dataset
  num_classes: 10
  in_channels: 1
models:
  name: mlp_dict
  num_blocks: 2
  input_dim: 512
  hidden_dim: 1024
  dropout_rate: 0.1
  num_copies: 1
  lamb_factor: 1.15
  lamb_start: -1
  lamb_end: 8
  lamb_step: 1
  k_start: 8
  k_end: 13
  k_step: 1
  in_channels: 1
clustering:
  name: augmentation_clustering
  lr: 0.005
  scheduler: ExponentialLR
  gamma: 0.9
  epochs: 50
  batch_size: 1000
  num_aug_copies: 1
representations:
  method: simclr
  temperature: 0.4
  loss: NTXentLoss
  scheduler: ExponentialLR
  lr: 0.003
  gamma: 0.98
  epochs: 500
  batch_size: 1000
experiment_name: mnistUnbal_iic_aug_simclr
device: cuda
seed: 42
save_dir: weights/mnistUnbal/augmentation_clustering/iic_aug/
save_name: iic_aug
augmentation: mnist_aug1
representation_model_dir: weights/mnistUnbal/representations/simclr/simclr_resnet18_266.00
representation_model_id: simclr_r18_266.00
